language: node_js

env:
  - CODECLIMATE_REPO_TOKEN=27355443bbc9aa3c50cffddc9f6fedf22948472b021e30c115e8749095b51ea0

addons:
  srcclr: true
  apt:
    packages:
    - graphicsmagick

node_js:
  - "6.9.0"
  - "6"
  - "7"

scripts:
  - yarn test:all
  - yarn test:react
after_success:
  - yarn ci-cover:coveralls
  - yarn ci-cover:prep-codeclimate
  - yarn ci-cover:codeclimate
  - rm -rf node_modules
  - sudo curl -sSL https://download.sourceclear.com/ci.sh | bash
